### ISSUE TITLE
Add eMortgage Logic as a sponsor

### ISSUE THREAD

**Issue by toddr** [Act-Conferences/yn2016#12]

**Comment by dwright** [comment]
I've written to Assurant to request graphics and text to use.

**Comment by dwright** [comment]
Here's the latest from them:

> I Jeff sent you the wrong company info. :-)  I'll get with him in the morning to correct it. We want to be listed under our parent company Assurant Mortgage Solutions instead of eMortgageLogic.
> I just didn't want you to start on anything before we get you updated info.
> Thanks.

**Comment by dwright** [comment]
Okay, this is the name they want now:   

Assurant Mortgage Solutions

And here is the URL

www.assurantspecialtyproperty.com/MortgageSolutions

Logo is in EPS, which github doesn't accept, so I will e-mail it to Todd.

**Comment by dwright** [comment]
(Still waiting on a bio from them.   They told me maybe by the end of the week)

**Comment by dwright** [comment]
Bio:

> Assurant Mortgage Solutions, a Perl user, is pleased to sponsor Yet Another Perl Conference: North America to raise awareness of the Perl programming language community and attract the best and the brightest Perl programmers to learn about us.  YAPC is a great event that provides Perl professionals a place to interact through open discussions, collaboration, design, and code.  We are excited to sponsor this event and continue our engagement with the Perl community.
