### ISSUE TITLE
Information for Zero to Perl class

### ISSUE THREAD

**Issue by dwright** [Act-Conferences/yn2016#15]
for the tutorials.html page:

Course description:

YAPC::NA, in conjunction with Infinity Interactive, is proud to announce "From Zero to Perl," a special course for programmers new to the Perl 5 programming language, to be taught by John Anderson on Sunday the 19th June.

The "Zero To Perl" course is designed to introduce programmers of any experience level to Perl 5 programming. (Non-programmers are welcomed as well!) This one-day course will give you the basic skills you'll need to program in simple Perl 5 for a variety of tasks, and will position you to both extend your Perl skills in the future, and enjoy the Perl Conference that will follow the training.

Speaker Biography:

John SJ Anderson has been using Perl for over fifteen years, since teaching it to himself as part of a desperate plan to finish his graduate work. He's been teaching computing concepts and introductory Perl and BioPerl to bioinformatics students at The Johns Hopkins University for the last ten years. In his free time, John contributes to several Open Source projects, moderates the perl-beginners mailing list, and organizes Hack Salem, a local nerd meetup in Salem, Oregon.

**Comment by toddr** [comment]
Provided in commit https://github.com/Act-Conferences/yn2016/commit/81c9794021725f81cf1f51fd743e474af5785337
